// Audits every built page in dist/ against site-plan §4.3 and writes docs/seo-audit.md.
// Fails (exit 1) on hard errors: not exactly one H1, missing/duplicate title or description,
// missing canonical, invalid JSON-LD. Length targets are reported as warnings.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) yield* walk(p);
    else if (name.endsWith('.html')) yield p;
  }
}
const decode = (s) => s.replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>');
const pages = [];
for (const file of walk('dist')) {
  const html = readFileSync(file, 'utf8');
  if (/http-equiv="refresh"/i.test(html.slice(0, 600))) continue; // old-URL redirect pages
  const route = '/' + file.slice(5).replace(/index\.html$/, '').replace(/\.html$/, '');
  const title = decode(html.match(/<title>([^<]*)<\/title>/)?.[1] ?? '');
  const description = decode(html.match(/<meta name="description" content="([^"]*)"/)?.[1] ?? '');
  const h1s = [...html.matchAll(/<h1[\s>]/g)].length;
  const canonical = html.match(/<link rel="canonical" href="([^"]*)"/)?.[1] ?? '';
  const ogImage = html.match(/<meta property="og:image" content="([^"]*)"/)?.[1] ?? '';
  const lang = html.match(/<html lang="([^"]*)"/)?.[1] ?? '';
  const ld = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map((m) => m[1]);
  let ldOk = true;
  const ldTypes = [];
  for (const block of ld) {
    try {
      const j = JSON.parse(block);
      for (const node of j['@graph'] ?? [j]) ldTypes.push(node['@type']);
    } catch {
      ldOk = false;
    }
  }
  pages.push({ route, title, description, h1s, canonical, ogImage, lang, ldOk, ldTypes, noindexPage: /\/(styleguide|thank-you|404)\/?$/.test(route) || route === '/404' });
}
pages.sort((a, b) => a.route.localeCompare(b.route));

const errors = [];
const warnings = [];
const indexable = pages.filter((p) => !p.noindexPage);
const dupes = (key) => {
  const seen = new Map();
  for (const p of indexable) seen.set(p[key], [...(seen.get(p[key]) ?? []), p.route]);
  return [...seen.entries()].filter(([k, v]) => k && v.length > 1);
};
for (const p of pages) {
  if (p.h1s !== 1) errors.push(`${p.route}: ${p.h1s} H1s (need exactly 1)`);
  if (!p.title) errors.push(`${p.route}: no <title>`);
  if (!p.ldOk) errors.push(`${p.route}: invalid JSON-LD`);
  if (p.lang !== 'en-IN') errors.push(`${p.route}: lang="${p.lang}"`);
  if (p.noindexPage) continue;
  if (!p.description) errors.push(`${p.route}: no meta description`);
  if (!p.canonical) errors.push(`${p.route}: no canonical`);
  if (!p.ogImage) errors.push(`${p.route}: no og:image`);
  if (p.title.length > 60 || p.title.length < 30) warnings.push(`${p.route}: title ${p.title.length} chars`);
  if (p.description.length < 140 || p.description.length > 160) warnings.push(`${p.route}: description ${p.description.length} chars`);
  if (!p.description.endsWith('Request a quote.') && !/privacy|thank|request-a-quote/.test(p.route)) warnings.push(`${p.route}: description doesn't end with "Request a quote."`);
  if (p.route.startsWith('/products/') && p.route !== '/products/' && !p.ldTypes.includes('Product') && !/foundry-consumables|hot-gas|thermal-insulation/.test(p.route))
    errors.push(`${p.route}: no Product JSON-LD`);
  if (p.route !== '/' && !p.ldTypes.includes('BreadcrumbList')) errors.push(`${p.route}: no BreadcrumbList JSON-LD`);
}
for (const [v, routes] of dupes('title')) errors.push(`duplicate title "${v}": ${routes.join(', ')}`);
for (const [, routes] of dupes('description')) errors.push(`duplicate description: ${routes.join(', ')}`);

const esc = (s) => s.replace(/\|/g, '\\|');
const md = [
  '# SEO audit',
  '',
  `Generated by \`node scripts/seo-audit.mjs\` on ${new Date().toISOString().slice(0, 10)} from \`dist/\` (${pages.length} pages; old-URL redirect pages skipped).`,
  '',
  `**${errors.length} errors, ${warnings.length} warnings.**`,
  '',
  ...(errors.length ? ['## Errors', '', ...errors.map((e) => `- ${e}`), ''] : []),
  ...(warnings.length ? ['## Warnings', '', ...warnings.map((w) => `- ${w}`), ''] : []),
  '## Pages',
  '',
  '| Route | Title (chars) | Description (chars) | H1 | JSON-LD |',
  '|---|---|---|---|---|',
  ...pages.map((p) => `| ${p.route}${p.noindexPage ? ' (noindex)' : ''} | ${esc(p.title)} (${p.title.length}) | ${p.description.length} | ${p.h1s} | ${[...new Set(p.ldTypes)].join(', ')} |`),
  '',
];
writeFileSync('docs/seo-audit.md', md.join('\n'));
console.log(`seo-audit: ${pages.length} pages, ${errors.length} errors, ${warnings.length} warnings → docs/seo-audit.md`);
for (const e of errors) console.error('  ✗ ' + e);
for (const w of warnings) console.warn('  ! ' + w);
if (errors.length) process.exit(1);
