// Collects every missing fact into docs/OUTSTANDING.md:
//   - literal [[TODO: …]] markers in src/
//   - todo('…') and fact(value, '…') calls, whose value is still null
//   - null fields in src/data/site.ts
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) yield* walk(p);
    else if (/\.(astro|ts|md|mdx|ya?ml)$/.test(p)) yield p;
  }
}

const items = new Map(); // text → Set(locations)
const add = (text, where) => {
  if (!items.has(text)) items.set(text, new Set());
  items.get(text).add(where);
};

for (const file of walk('src')) {
  const rel = relative('.', file);
  readFileSync(file, 'utf8').split('\n').forEach((line, i) => {
    const where = `${rel}:${i + 1}`;
    for (const m of line.matchAll(/\[\[TODO:\s*([^\]]+?)\s*\]\]/g)) {
      if (!/\$\{|^…$/.test(m[1])) add(m[1], where);
    }
    for (const m of line.matchAll(/\b(?:todo|fact)\((?:[^,()]+,\s*)?['"`]([^'"`]+)['"`]\)/g)) add(m[1], where);
  });
}

const site = readFileSync('src/data/site.ts', 'utf8');
const body = site.slice(site.indexOf('export const site'));
const nulls = [...body.matchAll(/^\s*(\w+):\s*null,/gm)].map((m) => m[1]);
const empties = [...body.matchAll(/^\s*(\w+):\s*\[\],/gm)].map((m) => m[1]);

const lines = [
  '# Outstanding facts and assets',
  '',
  `Generated by \`npm run todo\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`,
  'Supply these (see docs/content-checklist.md), then fill them in `src/data/site.ts` or the content files.',
  '',
  '## Empty fields in `src/data/site.ts`',
  '',
  ...nulls.map((k) => `- \`${k}\``),
  ...empties.map((k) => `- \`${k}\` (empty list)`),
  '',
  '## Placeholders in templates and content',
  '',
  ...[...items.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([text, where]) => `- ${text} — ${[...where].join(', ')}`),
  '',
];
writeFileSync('docs/OUTSTANDING.md', lines.join('\n'));
console.log(`todo: ${nulls.length + empties.length} empty site fields, ${items.size} placeholders → docs/OUTSTANDING.md`);
